### ISSUE TITLE
OutputAction is missing upon translation from Federated to Original network

### ISSUE THREAD

**Issue by pavellikin** [o3project/odenos#169] opened 2015-08-25 15:59 UTC
Dear Odenos community,

We are using Odenos inside our team and found incorrect behavior in Federator component.
The last part of decomposed flow has empty output action even though the federated flow itself has such action set.
Please have a look:
**Federated flow**
org.o3project.odenos.core.component.network.flow.basic.BasicFlow@b10002f[version=1,flowId=1,owner=pathprovisioner,enabled=true,priority=0,status=UP,matches=[org.o3project.odenos.core.component.network.flow.basic.BasicFlowMatch@27328d21[inNode=original-nw0_S0001-1,inPort=original-nw0_S0001-1_1_4009007_719285821855038]],path=[original-nw0_1_1005002_3_1001001_719285823882226, federator_boundary2_link01, original-nw1_LNK6614_6641, original-nw1_LNK6643_6634],**edgeActions={original-nw1_NE663=[org.o3project.odenos.core.component.network.flow.basic.FlowActionOutput@6f52920f[output=original-nw1_NE663_PRT6636]]}**,attributes={}]

**First decomposed flow (for original-nw0):** *org.o3project.odenos.core.component.network.flow.basic.BasicFlow@3b3c1b1c[version=1,flowId=1_1,owner=pathprovisioner,enabled=true,priority=0,status=UP,matches=[org.o3project.odenos.core.component.network.flow.basic.BasicFlowMatch@3f0398a3[inNode=S0001-1,inPort=1_4009007_719285821855038]],path=[1_1005002_3_1001001_719285823882226],edgeActions={S0002-1=[org.o3project.odenos.core.component.network.flow.basic.FlowActionOutput@7a011127[output=3_5009006_719285821855200]]},attributes={}]

**Last decomposed flow (for original-nw1):** org.o3project.odenos.core.component.network.flow.basic.BasicFlow@4dab5ea6[version=1,flowId=1_2,owner=pathprovisioner,enabled=true,priority=0,status=UP,matches=[org.o3project.odenos.core.component.network.flow.basic.BasicFlowMatch@3bf4fbcf[inNode=NE661,inPort=PRT6617]],path=[LNK6614_6641, LNK6643_6634],**edgeActions={}**,attributes={}]

Could you please elaborate this behavior? Is it correct or not?
We performed some investigation from our side and concluded that issue is located in FederatorOnFlow.java file, bit (lines 347-356):

``` java
      edgeNode = fedLink.getDstNode();
    }

    // convert action
    try {
      orgFlow.putEdgeActions(
          convertAction(fedNwId, edgeNode, orgFlow.getEdgeActions()));
    } catch (Exception e) {
      log.warn("failed convert flow's actions.");
    }
```

Could you please have a look at this bit from your perspective? 

Thanks,
Pavel.

**Comment by haizawa** [comment] 2015-08-27 01:17
It is not work as expected. We will investigate.I ask you to cooperate with you.
- Get the topology.
  Federated network, original-nw0, and original-nw1
  Example)
  
  > curl http://localhost:10080/systemmanager/components/original-nw0/topology -X GET
- Federator Get the bondary information
  Example)
  
  > curl http://localhost:10080/federator/settings/boundaries -X GET

**Comment by pavellikin** [comment] 2015-08-31 09:05
Hi,

I collected requested printouts. 
Unfortunately the log file is too long to be published at github. I uploaded the file to dropbox, please find it by the link - https://www.dropbox.com/s/u18crkwjms56xrh/topology.log?dl=0

Pavel.

**Comment by haizawa** [comment] 2015-09-03 01:18
Thank you.
We are the cause of the problem was found.
It was fixed in Pull request # 169.
Please update the develop branch.

**Comment by pavellikin** [comment] 2015-09-22 09:06
Hello,

We were able to test last odenos version with fix and it works well.
Thank you!

**Closed as completed** 2015-09-22 09:06 UTC
