### ISSUE TITLE
Wrong status of federated flow

### ISSUE THREAD

**Issue by aekom87** [o3project/odenos#184] opened 2015-09-22 10:21 UTC
Hi dear Odenos community,

we have encountered an issue with the status of a federated flow.

Odenos configuration is following:

```
            logic component
                      |
            federated net
           /               \
         /                   \
  orig net1               orig net2
```

Scenario is following:
1) logic component requests install of a flow on the federated net
1.1) status of the federated flow is NONE
2) flow is divided into 2 parts and each part is installed on an appropriate original network
2.1) flow status ESTABLISHING is sent from **both** original networks to the federated net
2.2) status of the federated flow is ESTABLISHING
3) flow status ESTABLISHED is sent from the original net1 **only**
3.1) status of the federated flow is **ESTABLISHED** - wrong!!! Flow is not yet established on the original net2. Therefore it should not be considered as ESTABLISHED on the federator level.

Could you please look into it?

Thanks in advance!
Andy

**Comment by haizawa** [comment] 2015-09-24 10:36
Thank you.
We are the cause of the problem was found.
It was fixed in Pull request # 185.
Please update the develop branch.

**Closed as completed** 2015-10-26 13:45 UTC
